export * from "./IAppointmentRepository"
export * from "./ICustomerRepository"
export * from "./IProfessionalRepository"
export * from "./IServiceRepository"
export * from "./ISalonRepository"
export * from "./IProductRepository"
export * from "./IAvailabilityRepository"
export * from "./ILeadRepository"
